subsubsection \<open>TempControl Initial Thread States\<close>

theory TempControlInitialThreadStates
  imports Model VarState PortState ThreadState
begin

text \<open>In the current HAMR implementation, all ports have queues of size 1, and the 
overflow policy of all port queues is {\tt DropEarliest}.   Therefore, 
HAMR AADL-HSM generation defines a empty queue with these attributes.  
The initial state of each thread has port states set to this empty queue.\<close>

definition empty_queue:: "int Queue" where [simp add]:
 "empty_queue = mk_empty_queue 1 DropOldest"

(*
  Component TempControlSoftwareSystem_s_Instance_tcproc_tempSensor Thread State Attributes
*)

text \<open>The following definitions are generated by HAMR to represent the 
initial state of the {\tt TempSensor} thread.\<close>

text \<open>Local thread variable state: The {\tt TempSensor} thread has no variables, so
the @{term VarState} is an empty map.\<close>

definition TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_tvar_initial :: "int VarState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_tvar_initial = Map.empty"

text \<open>Infrastructure Input Port State: The {\tt TempSensor} thread has no input ports,
the infrastructure input port state @{term infi} is an empty map.\<close>

definition TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_infi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_infi_initial = Map.empty"

text \<open>Application Input Port State: The {\tt TempSensor} thread has no input ports,
the application input port state @{term appi} is an empty map.\<close>

definition TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_appi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_appi_initial = Map.empty"

text \<open>Application Output Port State: The {\tt TempSensor} thread has two output ports
{\tt currentTemp} and {\tt tempChanged}, so the @{term PortIds} for those ports 
are mapped to empty queues.\<close>

definition TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_appo_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_appo_initial = map_of [((PortId 0), empty_queue),((PortId 1), empty_queue)]"

text \<open>Infrastructure Output Port State: The {\tt TempSensor} thread has two output ports
{\tt currentTemp} and {\tt tempChanged}, so the @{term PortIds} for those ports 
are mapped to empty queues.\<close>

definition TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_info_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_info_initial = map_of [((PortId 0), empty_queue),((PortId 1), empty_queue)]"

text \<open>The @{term DispatchStatus} for the thread is set to @{term NotEnabled}.\<close>

definition TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_disp_initial :: "DispatchStatus" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_disp_initial = NotEnabled"

text \<open>The values above are combined into a record to form the initial thread state for {\tt TempSensor}
thread.\<close>

definition TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_initial :: "int ThreadState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_initial =
     ( tstate
        TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_infi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_appi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_appo_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_info_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_tvar_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempSensor_disp_initial
     )"

text \<open>State definitions for the remaining components are similar.\<close>
(*
  Component TempControlSoftwareSystem_s_Instance_tcproc_fan Thread State Attributes
*)
definition TempControlSoftwareSystem_s_Instance_tcproc_fan_tvar_initial :: "int VarState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_fan_tvar_initial = Map.empty"

definition TempControlSoftwareSystem_s_Instance_tcproc_fan_infi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_fan_infi_initial = map_of [((PortId 2), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_fan_appi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_fan_appi_initial = map_of [((PortId 2), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_fan_appo_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_fan_appo_initial = map_of [((PortId 3), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_fan_info_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_fan_info_initial = map_of [((PortId 3), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_fan_disp_initial :: "DispatchStatus" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_fan_disp_initial = NotEnabled"

definition TempControlSoftwareSystem_s_Instance_tcproc_fan_initial :: "int ThreadState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_fan_initial =
     ( tstate
        TempControlSoftwareSystem_s_Instance_tcproc_fan_infi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_fan_appi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_fan_appo_initial
        TempControlSoftwareSystem_s_Instance_tcproc_fan_info_initial
        TempControlSoftwareSystem_s_Instance_tcproc_fan_tvar_initial
        TempControlSoftwareSystem_s_Instance_tcproc_fan_disp_initial
     )"

(*
  Component TempControlSoftwareSystem_s_Instance_tcproc_tempControl Thread State Attributes
*)
definition TempControlSoftwareSystem_s_Instance_tcproc_tempControl_tvar_initial :: "int VarState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempControl_tvar_initial = Map.empty"

definition TempControlSoftwareSystem_s_Instance_tcproc_tempControl_infi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempControl_infi_initial = map_of [((PortId 4), empty_queue),((PortId 5), empty_queue),((PortId 6), empty_queue),((PortId 8), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_tempControl_appi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempControl_appi_initial = map_of [((PortId 4), empty_queue),((PortId 5), empty_queue),((PortId 6), empty_queue),((PortId 8), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_tempControl_appo_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempControl_appo_initial = map_of [((PortId 7), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_tempControl_info_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempControl_info_initial = map_of [((PortId 7), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_tempControl_disp_initial :: "DispatchStatus" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempControl_disp_initial = NotEnabled"

definition TempControlSoftwareSystem_s_Instance_tcproc_tempControl_initial :: "int ThreadState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_tempControl_initial =
     ( tstate
        TempControlSoftwareSystem_s_Instance_tcproc_tempControl_infi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempControl_appi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempControl_appo_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempControl_info_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempControl_tvar_initial
        TempControlSoftwareSystem_s_Instance_tcproc_tempControl_disp_initial
     )"

(*
  Component TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface Thread State Attributes
*)
definition TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_tvar_initial :: "int VarState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_tvar_initial = Map.empty"

definition TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_infi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_infi_initial = map_of [((PortId 9), empty_queue),((PortId 11), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_appi_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_appi_initial = map_of [((PortId 9), empty_queue),((PortId 11), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_appo_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_appo_initial = map_of [((PortId 10), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_info_initial :: "int PortState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_info_initial = map_of [((PortId 10), empty_queue)]"

definition TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_disp_initial :: "DispatchStatus" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_disp_initial = NotEnabled"

definition TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_initial :: "int ThreadState" where [simp add]:
  "TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_initial =
     ( tstate
        TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_infi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_appi_initial
        TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_appo_initial
        TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_info_initial
        TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_tvar_initial
        TempControlSoftwareSystem_s_Instance_tcproc_operatorInterface_disp_initial
     )"

end